FROM python:3-alpine

COPY . /app
WORKDIR /app

RUN apk add \
        fontconfig \
        zlib-dev \
        jpeg-dev \
        gcc musl-dev \
    && \
    pip3 install -r requirements.txt

EXPOSE 8013
ENTRYPOINT [ "python3", "run.py" ]
